services:
  api:
    build: ./api
    container_name: temporal_api
    ports:
      - "3023:3023"
    environment:
      - TEMPORAL_ADDRESS=host.docker.internal:7233
      - PORT=3023
    volumes:
      - ./api/src:/app/src
    working_dir: /app
    command: sh -c "npm install && node src/server.js"
    restart: unless-stopped
    networks:
      - temporal-network
      - webnet
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    build: ./api
    container_name: temporal_worker
    working_dir: /app
    command: sh -c "npm install && node src/worker.js"
    volumes:
      - ./api/src:/app/src
    environment:
      - TEMPORAL_ADDRESS=host.docker.internal:7233
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CSE_ID=${GOOGLE_CSE_ID}
    networks:
      - temporal-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    build: ./web
    container_name: temporal_web
    ports:
      - "8085:80"
    volumes:
      - ./web/public:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - webnet

networks:
  temporal-network:
    external: true
  webnet:
    driver: bridge
